version: '3.3'
services:
  alertmanager:
    image: prom/alertmanager:v0.13.0
    command:
     - --config.file=/etc/alertmanager/alertmanager.yml
    volumes:
     - alertmanager:/data
    networks:
     - default
    configs:
     -
      source: autoscale_lb_alertmanager
      target: /etc/alertmanager/alertmanager.yml
    logging:
      driver: json-file
  app:
    image: nodeweb:latest
    labels:
      orbiter: 'true'
    environment:
      SERVICE_PORTS: '8080'
      VIRTUAL_HOST: '*'
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      labels:
        orbiter: 'true'
      update_config:
        delay: 3s
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 5s
        max_attempts: 3
      placement:
        constraints:
         - node.role != manager
      resources:
        reservations:
          cpus: '0.25'
          memory: 32M
        limits:
          cpus: '0.5'
          memory: 64M
  haproxy_exporter:
    image: prom/haproxy-exporter:v0.9.0
    command:
     - --haproxy.scrape-uri=http://stats:stats@lb:1936/haproxy?stats;csv
    networks:
     - default
    logging:
      driver: json-file
  lb:
    image: dockercloud/haproxy:latest
    environment:
      ADDITIONAL_SERVICES: project_dir:app
    ports:
     - 9095:80
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      update_config:
        delay: 3s
      restart_policy:
        condition: on-failure
        delay: 3s
        window: 5s
        max_attempts: 3
      placement:
        constraints:
         - node.role == manager
  orbiter:
    image: gianarb/orbiter:d2c82ad
    command:
     - daemon
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - default
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
         - node.role == manager
  prometheus:
    image: prom/prometheus:v2.1.0
    command:
     - --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
    volumes:
     - prometheus:/data
    networks:
     - default
    configs:
     -
      source: autoscale_lb_alert_rules
      target: /etc/prometheus/alerts.yml
     -
      source: autoscale_lb_prom_config
      target: /etc/prometheus/prometheus.yml
    logging:
      driver: json-file
  unsee:
    image: cloudflare/unsee:v0.9.1
    environment:
      ALERTMANAGER_URIS: default:http://alertmanager:9093
    ports:
     - 8082:8080
    networks:
     - default
    logging:
      driver: json-file
networks:
  default:
    driver: overlay
volumes:
  alertmanager:
    driver: local
  prometheus:
    driver: local
configs:
  autoscale_lb_alert_rules:
    external: true
  autoscale_lb_alertmanager:
    external: true
  autoscale_lb_prom_config:
    external: true

